/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomPanel: typeof import('./components/BottomPanel.vue')['default']
    CarouselPromo: typeof import('./components/CarouselPromo.vue')['default']
    CommCards: typeof import('./components/CommCards.vue')['default']
    MainNav: typeof import('./components/MainNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Socials: typeof import('./components/Socials.vue')['default']
    TopPanel: typeof import('./components/TopPanel.vue')['default']
  }
}
