/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/CommissionsView': RouteRecordInfo<'/CommissionsView', '/CommissionsView', Record<never, never>, Record<never, never>>,
    '/LibraryView': RouteRecordInfo<'/LibraryView', '/LibraryView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/PortfolioView': RouteRecordInfo<'/PortfolioView', '/PortfolioView', Record<never, never>, Record<never, never>>,
    '/SupportView': RouteRecordInfo<'/SupportView', '/SupportView', Record<never, never>, Record<never, never>>,
    '/TOS': RouteRecordInfo<'/TOS', '/TOS', Record<never, never>, Record<never, never>>,
  }
}
